GET http://localhost:8080/api/v1/photos HTTP/1.1

POST http://localhost:8080/api/v1/photos HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZmJhNDFlYi02MWZlLTRjOTUtOWJmZS01YzRlZTFmZDA3NmEiLCJleHAiOjExNTE2MjM5MDIyfQ.eNPqAwZzzPW8o8F8gi6puXhnxmdX6aRiJf8iuqOPcLE

  {
    "mime": "image\/png",
    "base64_img": "iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="
  }

GET  http://localhost:8080/img/ac53884f-1b0d-4396-b981-e060720e7ce7 HTTP/1.1