GET http://localhost:8080/api/v1/photos HTTP/1.1

GET http://localhost:8080/api/v1/albums HTTP/1.1

GET http://localhost:8080/img/ebc534ab-89a9-48bd-a141-adc09dabba8c?height=180 HTTP/1.1

POST http://localhost:8080/api/v1/login
content-type: application/json
  
  {
    "email": "example@example.com",
    "password": "admin"
  }

POST http://localhost:8080/api/v1/photos HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZmJhNDFlYi02MWZlLTRjOTUtOWJmZS01YzRlZTFmZDA3NmEiLCJleHAiOjk1MTYyMzkwMjJ9.OuFH6oiYVaBkFV2XZBb_M2CWNYw78tcAGMescPnN0c8
  
  {
    "mime": "image\/png",
    "base64_img": "iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="
  }

POST http://localhost:8080/api/v1/albums HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZmJhNDFlYi02MWZlLTRjOTUtOWJmZS01YzRlZTFmZDA3NmEiLCJleHAiOjk1MTYyMzkwMjJ9.OuFH6oiYVaBkFV2XZBb_M2CWNYw78tcAGMescPnN0c8
  
  {
    "name": "Just Album"
  }

GET  http://localhost:8080/api/v1/photos/ebc534ab-89a9-48bd-a141-adc09dabba8c/comments HTTP/1.1

POST http://localhost:8080/api/v1/photos/ebc534ab-89a9-48bd-a141-adc09dabba8c/comments HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZmJhNDFlYi02MWZlLTRjOTUtOWJmZS01YzRlZTFmZDA3NmEiLCJleHAiOjk1MTYyMzkwMjJ9.OuFH6oiYVaBkFV2XZBb_M2CWNYw78tcAGMescPnN0c8
  
  {
    "content": "just comment for a photo"
  }

POST http://localhost:8080/api/v1/users HTTP/1.1
content-type: application/json
# authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZmJhNDFlYi02MWZlLTRjOTUtOWJmZS01YzRlZTFmZDA3NmEiLCJleHAiOjk1MTYyMzkwMjJ9.OuFH6oiYVaBkFV2XZBb_M2CWNYw78tcAGMescPnN0c8
  
  {
    "first_name": "Jane",
    "last_name": "Doe",
    "password": "admin",
    "email": "janedoe@example.com",
    "role":"regular"
  }

GET http://localhost:8080/api/v1/photos/ebc534ab-89a9-48bd-a141-adc09dabba8c/rates HTTP/1.1

POST http://localhost:8080/api/v1/photos/ebc534ab-89a9-48bd-a141-adc09dabba8c/rates HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZmJhNDFlYi02MWZlLTRjOTUtOWJmZS01YzRlZTFmZDA3NmEiLCJleHAiOjk1MTYyMzkwMjJ9.OuFH6oiYVaBkFV2XZBb_M2CWNYw78tcAGMescPnN0c8
  
  {
    "stars": 5
  }